# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b59f4bedf162375d9261063c3bf2feb1"
name = "member_integration"
handle = "member_integration"
application_url = "https://copyrighted-implications-theft-racial.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "webhook-manager-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers, write_discounts, write_orders, write_products"

[auth]
redirect_urls = [
  "https://copyrighted-implications-theft-racial.trycloudflare.com/auth/callback",
  "https://copyrighted-implications-theft-racial.trycloudflare.com/auth/shopify/callback",
  "https://copyrighted-implications-theft-racial.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/order_created"

  [[webhooks.subscriptions]]
  topics = [ "orders/delete" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/order_delete"

  [[webhooks.subscriptions]]
  topics = [ "orders/edited" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/order_edited"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/order_fulfillment"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/order_update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "https://membiintegrationshopify-production.up.railway.app/webhooks/product_updated"

[pos]
embedded = false
