# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b59f4bedf162375d9261063c3bf2feb1"
application_url = "https://smoke-ch-sit-bench.trycloudflare.com"
embedded = true
name = "member_integration"
handle = "member_integration"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "webhook-manager-app.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order_created"

  [[webhooks.subscriptions]]
  topics = [ "orders/delete" ]
  uri = "/webhooks/app/order_delete"

  [[webhooks.subscriptions]]
  topics = [ "orders/edited" ]
  uri = "/webhooks/app/order_edited"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/app/order_fulfillment"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/app/order_update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/product_updated"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_orders,write_products,write_discounts"

[auth]
redirect_urls = [
  "https://smoke-ch-sit-bench.trycloudflare.com/auth/callback",
  "https://smoke-ch-sit-bench.trycloudflare.com/auth/shopify/callback",
  "https://smoke-ch-sit-bench.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
