{
  id: 6198636642604,
  admin_graphql_api_id: "gid://shopify/Order/6198636642604",
  app_id: 1354745,
  browser_ip: "223.197.189.54",
  buyer_accepts_marketing: false,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: null,
  checkout_id: 38569755803948,
  checkout_token: "37199ac0110049119948ba9460fa065f",
  client_details: {
    accept_language: null,
    browser_height: null,
    browser_ip: "223.197.189.54",
    browser_width: null,
    session_hash: null,
    user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  },
  closed_at: null,
  company: null,
  confirmation_number: "0HRHNV18I",
  confirmed: true,
  contact_email: null,
  created_at: "2025-01-23T03:43:48-05:00",
  currency: "HKD",
  current_shipping_price_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  current_subtotal_price: "100.00",
  current_subtotal_price_set: {
    shop_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
  },
  current_total_additional_fees_set: null,
  current_total_discounts: "0.00",
  current_total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  current_total_duties_set: null,
  current_total_price: "100.00",
  current_total_price_set: {
    shop_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  customer_locale: "zh-TW",
  device_id: null,
  discount_codes: [],
  duties_included: false,
  email: "",
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: null,
  landing_site: null,
  landing_site_ref: null,
  location_id: 103709376812,
  merchant_business_entity_id: "MTkxNzQwODY0ODEy",
  merchant_of_record_app_id: null,
  name: "#1062",
  note: null,
  note_attributes: [],
  number: 62,
  order_number: 1062,
  order_status_url: "https://webhook-manager-app.myshopify.com/91740864812/orders/37b8cc91243bb608328d4bcf2121c525/authenticate?key=7a13032558ab3fb580b58c6d67817fa6",
  original_total_additional_fees_set: null,
  original_total_duties_set: null,
  payment_gateway_names: [ "manual" ],
  phone: null,
  po_number: null,
  presentment_currency: "HKD",
  processed_at: "2025-01-23T03:43:48-05:00",
  reference: null,
  referring_site: null,
  source_identifier: null,
  source_name: "shopify_draft_order",
  source_url: null,
  subtotal_price: "100.00",
  subtotal_price_set: {
    shop_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
  },
  tags: "",
  tax_exempt: false,
  tax_lines: [],
  taxes_included: false,
  test: false,
  token: "37b8cc91243bb608328d4bcf2121c525",
  total_cash_rounding_payment_adjustment_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  total_cash_rounding_refund_adjustment_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  total_discounts: "0.00",
  total_discounts_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  total_line_items_price: "100.00",
  total_line_items_price_set: {
    shop_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
  },
  total_outstanding: "0.00",
  total_price: "100.00",
  total_price_set: {
    shop_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "100.00",
      currency_code: "HKD",
    },
  },
  total_shipping_price_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
    presentment_money: {
      amount: "0.00",
      currency_code: "HKD",
    },
  },
  total_tip_received: "0.00",
  total_weight: 0,
  updated_at: "2025-01-23T03:43:49-05:00",
  user_id: 116651032876,
  billing_address: null,
  customer: null,
  discount_applications: [],
  fulfillments: [],
  line_items: [
    {
      id: 15515388477740,
      admin_graphql_api_id: "gid://shopify/LineItem/15515388477740",
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "Green Snowboard",
      price: "100.00",
      price_set: {
        shop_money: {
          amount: "100.00",
          currency_code: "HKD",
        },
        presentment_money: {
          amount: "100.00",
          currency_code: "HKD",
        },
      },
      product_exists: true,
      product_id: 9797441945900,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "",
      taxable: true,
      title: "Green Snowboard",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: {
          amount: "0.00",
          currency_code: "HKD",
        },
        presentment_money: {
          amount: "0.00",
          currency_code: "HKD",
        },
      },
      variant_id: 50451770802476,
      variant_inventory_management: null,
      variant_title: null,
      vendor: "webhook-manager-app",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    }
  ],
  payment_terms: null,
  refunds: [],
  shipping_address: null,
  shipping_lines: [],
  returns: [],